name: Build XPU extensions

on:
  workflow_dispatch:
  # pull_request:

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    # make sure tags are fetched so we can get a version
    - run: |
        git fetch --prune --unshallow --tags

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

